services:
  php:
    container_name: check24-php
    build:
      context: ./docker/php
      args:
        uid: 1000
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
  nginx:
    container_name: check24-nginx
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
